apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nxfe21buz-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nxfe21buz-dotnet-basic-gitops